resources:
  - ../../base

patches:
  - path: replicas-patch.yaml

images:
  - name: drawing-app-backend
    newName: docker.io/sova11/drawing-app-backend
    newTag: eda24dd
  - name: drawing-app-frontend
    newName: docker.io/sova11/drawing-app-frontend
    newTag: eda24dd
